// This contains the Typescript code for the component
// It defines several things Angular needs to know about the component 
import { Component } from '@angular/core';  // Give me access to basic Angular features
import { RouterOutlet } from '@angular/router'; // Give me access to the Angular router

// @Component identifies the attributes/characteristics of the component
@Component({
  // Selector is the tag-name used in the html to reference the component
  selector: 'app-root',    // where in to insert the HTML generated by Angular for the component
  imports: [RouterOutlet],
  templateUrl: './app.html', // Name of the html for the component (content of the component)
  styleUrl: './app.css'     // Name of the css files for component (styling of component)
})

// export allows other processes outside this Typescript file (like Angular)
//      to access stuff in the Typescript
export class App {  // The class name is used in import statements to reference the the 
                    // data/methods in this export 
  protected title = 'myFirstAngularApp';  // data Anggular can used 
}
